# Generated by Django 4.0.5 on 2022-08-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destiny', models.CharField(max_length=100)),
                ('departure_date', models.DateField()),
                ('date_back', models.DateField()),
                ('date_search', models.DateField()),
                ('informations', models.TextField(blank=True, max_length=200)),
                ('travel_class', models.CharField(choices=[('ECON', 'Economic'), ('EXEC', 'Executiva'), ('STCL', 'First class')], default=0, max_length=4)),
            ],
        ),
    ]
