# Generated by Django 4.0.5 on 2022-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='travel_class',
            field=models.CharField(choices=[('ECON', 'Economic'), ('EXEC', 'Executive'), ('STCL', 'First class')], default=0, max_length=4),
        ),
    ]
