# Generated by Django 4.0.5 on 2022-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_travel_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_back',
            field=models.DateField(verbose_name='Data de volta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date_search',
            field=models.DateField(verbose_name='Data da pesquisa'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(verbose_name='Data de ida'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='destiny',
            field=models.CharField(max_length=100, verbose_name='Destino'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='informations',
            field=models.TextField(blank=True, max_length=200, verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origin',
            field=models.CharField(max_length=100, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='travel_class',
            field=models.CharField(choices=[('ECON', 'Economic'), ('EXEC', 'Executive'), ('STCL', 'First class')], default=0, max_length=4, verbose_name='Classe'),
        ),
    ]
